[program:dershane-worker-high]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/dershane/artisan queue:work --queue=notifications,finance --sleep=3 --tries=3 --timeout=60 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/www/dershane/storage/logs/supervisor-high.log
stopwaitsecs=360

[program:dershane-worker-default]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/dershane/artisan queue:work --queue=reports,documents,media,default --sleep=3 --tries=3 --timeout=120 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/www/dershane/storage/logs/supervisor-default.log
stopwaitsecs=360
