<?php

declare(strict_types=1);

namespace App\Providers;

use Illuminate\Support\ServiceProvider;

class RepositoryServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     */
    public function register(): void
    {
        $this->app->bind(
            \App\Core\Repositories\Interfaces\UserRepositoryInterface::class,
            \App\Core\Repositories\UserRepository::class
        );
        $this->app->bind(
            \App\Core\Repositories\Interfaces\RoleRepositoryInterface::class,
            \App\Core\Repositories\RoleRepository::class
        );
        $this->app->bind(
            \App\Core\Repositories\Interfaces\PageRepositoryInterface::class,
            \App\Core\Repositories\PageRepository::class
        );
        $this->app->bind(
            \App\Core\Repositories\Interfaces\MediaRepositoryInterface::class,
            \App\Core\Repositories\MediaRepository::class
        );
        $this->app->bind(
            \App\Core\Repositories\Interfaces\MediaFolderRepositoryInterface::class,
            \App\Core\Repositories\MediaFolderRepository::class
        );
        $this->app->bind(
            \App\Core\Repositories\Interfaces\PlatformSettingRepositoryInterface::class,
            \App\Core\Repositories\PlatformSettingRepository::class
        );
        $this->app->bind(
            \App\Core\Repositories\Interfaces\SettingGroupRepositoryInterface::class,
            \App\Core\Repositories\SettingGroupRepository::class
        );
        $this->app->bind(
            \App\Core\Repositories\Interfaces\BlogRepositoryInterface::class,
            \App\Core\Repositories\BlogRepository::class
        );
        $this->app->bind(
            \App\Core\Repositories\Interfaces\BlogCategoryRepositoryInterface::class,
            \App\Core\Repositories\BlogCategoryRepository::class
        );
        $this->app->bind(
            \App\Core\Repositories\Interfaces\BlogTagRepositoryInterface::class,
            \App\Core\Repositories\BlogTagRepository::class
        );
        $this->app->bind(
            \App\Core\Repositories\Interfaces\CommentRepositoryInterface::class,
            \App\Core\Repositories\CommentRepository::class
        );
        $this->app->bind(
            \App\Core\Repositories\Interfaces\TeacherRepositoryInterface::class,
            \App\Core\Repositories\TeacherRepository::class
        );
        $this->app->bind(
            \App\Core\Repositories\Interfaces\TeacherDocumentRepositoryInterface::class,
            \App\Core\Repositories\TeacherDocumentRepository::class
        );
        $this->app->bind(
            \App\Core\Repositories\Interfaces\TeacherScheduleRepositoryInterface::class,
            \App\Core\Repositories\TeacherScheduleRepository::class
        );
        $this->app->bind(
            \App\Core\Repositories\Interfaces\TeacherPerformanceRepositoryInterface::class,
            \App\Core\Repositories\TeacherPerformanceRepository::class
        );
        $this->app->bind(
            \App\Core\Repositories\Interfaces\CourseRepositoryInterface::class,
            \App\Core\Repositories\CourseRepository::class
        );
        $this->app->bind(
            \App\Core\Repositories\Interfaces\CourseLevelRepositoryInterface::class,
            \App\Core\Repositories\CourseLevelRepository::class
        );
        $this->app->bind(
            \App\Core\Repositories\Interfaces\ClassroomRepositoryInterface::class,
            \App\Core\Repositories\ClassroomRepository::class
        );
        $this->app->bind(
            \App\Core\Repositories\Interfaces\ClassScheduleRepositoryInterface::class,
            \App\Core\Repositories\ClassScheduleRepository::class
        );
        $this->app->bind(
            \App\Core\Repositories\Interfaces\StudentRepositoryInterface::class,
            \App\Core\Repositories\StudentRepository::class
        );
        $this->app->bind(
            \App\Core\Repositories\Interfaces\StudentEnrollmentRepositoryInterface::class,
            \App\Core\Repositories\StudentEnrollmentRepository::class
        );
        $this->app->bind(
            \App\Core\Repositories\Interfaces\AttendanceSessionRepositoryInterface::class,
            \App\Core\Repositories\AttendanceSessionRepository::class
        );
        $this->app->bind(
            \App\Core\Repositories\Interfaces\AttendanceRepositoryInterface::class,
            \App\Core\Repositories\AttendanceRepository::class
        );
        $this->app->bind(
            \App\Core\Repositories\Interfaces\ExamRepositoryInterface::class,
            \App\Core\Repositories\ExamRepository::class
        );
        $this->app->bind(
            \App\Core\Repositories\Interfaces\ExamResultRepositoryInterface::class,
            \App\Core\Repositories\ExamResultRepository::class
        );
        $this->app->bind(
            \App\Core\Repositories\Interfaces\AssignmentRepositoryInterface::class,
            \App\Core\Repositories\AssignmentRepository::class
        );
        $this->app->bind(
            \App\Core\Repositories\Interfaces\AssignmentSubmissionRepositoryInterface::class,
            \App\Core\Repositories\AssignmentSubmissionRepository::class
        );
        $this->app->bind(
            \App\Core\Repositories\Interfaces\InvoiceRepositoryInterface::class,
            \App\Core\Repositories\InvoiceRepository::class
        );
        $this->app->bind(
            \App\Core\Repositories\Interfaces\PaymentRepositoryInterface::class,
            \App\Core\Repositories\PaymentRepository::class
        );
        $this->app->bind(
            \App\Core\Repositories\Interfaces\NotificationRepositoryInterface::class,
            \App\Core\Repositories\NotificationRepository::class
        );
        $this->app->bind(
            \App\Core\Repositories\Interfaces\AnnouncementRepositoryInterface::class,
            \App\Core\Repositories\AnnouncementRepository::class
        );
        $this->app->bind(
            \App\Core\Repositories\Interfaces\ParentRepositoryInterface::class,
            \App\Core\Repositories\ParentRepository::class
        );
        $this->app->bind(
            \App\Core\Repositories\Interfaces\TeacherPortalRepositoryInterface::class,
            \App\Core\Repositories\TeacherPortalRepository::class
        );
        $this->app->bind(
            \App\Core\Repositories\Interfaces\ReportingRepositoryInterface::class,
            \App\Core\Repositories\ReportingRepository::class
        );
        $this->app->bind(
            \App\Core\Repositories\Interfaces\LeadRepositoryInterface::class,
            \App\Core\Repositories\LeadRepository::class
        );
        $this->app->bind(
            \App\Core\Repositories\Interfaces\LeadActivityRepositoryInterface::class,
            \App\Core\Repositories\LeadActivityRepository::class
        );
        $this->app->bind(
            \App\Core\Repositories\Interfaces\AdmissionRepositoryInterface::class,
            \App\Core\Repositories\AdmissionRepository::class
        );
        $this->app->bind(
            \App\Core\Repositories\Interfaces\EnrollmentRepositoryInterface::class,
            \App\Core\Repositories\EnrollmentRepository::class
        );
        $this->app->bind(
            \App\Core\Repositories\Interfaces\DocumentRepositoryInterface::class,
            \App\Core\Repositories\DocumentRepository::class
        );
    }

    /**
     * Bootstrap any application services.
     */
    public function boot(): void
    {
        //
    }
}
